### ISSUE TITLE
Conduct Domain Research

### ISSUE THREAD

**Issue by RainbowGamer707** [DECO3500-Team-Aces/DesignProject#1]

**Comment by gabi-lopez1** [comment]
Research : Everyone research 3-4 articles and include the following on this google docuement underneath your name [https://docs.google.com/document/d/1vP3onicPOQCDvlFB2DT_IrVp9DFdMTJsjzgdTd9iEXA/edit](url) 

- [ ] Article links + title 
- [ ] Information, quotes (can be copied/pasted) 
- [ ] Summary of what the article says (in your own words)

**Comment by gabi-lopez1** [comment]
@LungYuLin - let's both focus on 1-2 aritcles for existing solutions and 1-2 articles on the domain and issues. This will help us write the domain description for the proposal

**Comment by RainbowGamer707** [comment]
I've put 3 articles that I found interesting into the document, with a brief overview of what it contains
