### ISSUE TITLE
Initial Domain Interviews

### ISSUE THREAD

**Issue by ScariestWheat** [DECO3500-Team-Aces/DesignProject#11]
### Description
Further domain research to fully understand the current learning environment for children regarding their literacy skills. How do they currently collaborate on these skills (do they)? What technologies are available for students? and so on. Get to know the context of the domain further.

We plan to interview both parents and teachers of Primary school students to gain further insights into how these students are currently developing their literacy skills. 

### Links to Documents
[Teacher Interview Protocol](https://docs.google.com/document/d/1iSYjD2aBtMM1_6ucnSCmCOXIZDb_b32lr9Zf01iDklo/edit?usp=sharing)
[Teacher Interview Results](https://docs.google.com/document/d/1uQH4R1Qk8w7-2kt2ZslDl8yFbF2QSs3icF3XlMWPY4g/edit?usp=sharing)

[Parent Interview Protocol](https://docs.google.com/document/d/12zUpBX25CwHHxa-5OhWiV9Exiuid4Im7O90RCnH2-kw/edit?usp=sharing)
[Parent Interview Results](https://docs.google.com/document/d/19zWbTrbdZr_0l8Ij5KHAYj1e_mgL7_MDr5QEHP7zolk/edit?usp=sharing)

### To Do
- [x] Write Protocol (questions)
- [x] Determine interviewers
- [ ] Conduct interviews
- [ ] Analyse and Evaluate Results

**Comment by gabi-lopez1** [comment]
- [ ] @ScariestWheat - please do 2 interviews with primary teachers
- [ ] @gabi-lopez1 - do 1 interview with teacher, 1 with parents 
- [ ] @LungYuLin - do 1 interview with teacher 
- [ ] @Asmamzh - do 2 interviews with parents of young children
